### ISSUE TITLE
Documentation about importStrategy

### ISSUE THREAD

**Issue by paramosr** [jenkinsci/osf-builder-suite-for-sfcc-data-import-plugin#7]
Hello,

I am using the Jenkins plugin to import data through different SFCC environments.
The fact is that the plugin give the importStrategy option to import data follow the 'DELTA' strategy (only import the new changes).
In some cases I want to import data 'REPLACING' the actual data and not 'MERGING'. 
For example if I delete an attribute, I want to delete also in the target environment.
I try without the _importStrategy_ option and I see on the log that executes a `FULL import` instead of `DELTA import` but still the import is not done via the MERGE type.

First of all I would like to know the difference between both options and secondly I would like to know if there is the possibility to import using the 'MERGE' type.

There is no documentation about this option and it would be of great help to me. Thanks

Best regards,

**Comment by danechitoaie** [comment]
In both cases the import is MERGE mode. SFCC only supports the MERGE mode for metadata imports.

See https://documentation.b2c.commercecloud.salesforce.com/DOC1/topic/com.demandware.dochelp/OCAPI/current/data/Documents/SiteArchiveImportConfiguration.html#id-403860140

The mode supported by SFCC only has one value `Enum {merge}`.

Now as for the difference between importStrategy (FULL vs DELTA):
1. When FULL is used all metadata is imported (still in merge mode, as SFCC only supports merge mode - see above)
2. When DELTA is used the plugin checks the previously successful build and checks what files have been imported then. And in current build only the files that have been changed since then (since last previously successful build) will be imported this time.

If you want to always have the data exactly as you have it in metadata in Git, you can reset the sandbox before each build. This will delete ALL data from it and then import only what you have in your Git repo in the metadata folder.
